[world]
name = "Dosis"
description = "Dosis Game."
seed = "dosis_game"

[namespace]
default = "dosis_game"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = ""
private_key = ""

[writers]
"dosis_game" = [
    "dosis_game-drug_crafting_system"
]
