[package]
name = "dosis_game"
version = "1.0.0"
cairo-version = "2.12.2"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = "1.7.0"
dojo_cairo_macros = "1.7.0"
starknet = "2.12.2"
openzeppelin = "1.0.0"

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world"
]

[dev-dependencies]
cairo_test = "=2.12.2"
dojo_cairo_test = "1.7.0"

[profile.dev]
[profile.sepolia]
[profile.mainnet]